### ISSUE TITLE
Team 111 Code Review

### ISSUE THREAD

**Issue by expjazz** [Rumbie-Mudzie7/Capstone-Html-and-Css-Project#3]
#### Great work as usual.

- Make the color of the text in the header menus a little lighter.
- The colors on the buttons are very faint. 
- The colors in the footer also look faint.
- The logo is really creative and nice.
- We noticed the lack of flexbox.
- A hover effect in the navbar would be good.

**Comment by Rumbie-Mudzie7** [comment]
Thank you for the review.  Will definitely look into the suggestions.  Much appreciated.
